---
AWSTemplateFormatVersion: '2010-09-09'

Description: 'Pratice template from Irene Jia'

Resources:
  EC2Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM
      RoleName: 'ireneEC2Role'
  
  Ec2SsmInstanceProfile:
      Type: AWS::IAM::InstanceProfile
      Properties: 
        Path: /
        Roles: 
          - !Ref EC2Role

  MyLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        IamInstanceProfile: 
          Arn: !GetAtt Ec2SsmInstanceProfile.Arn
        DisableApiTermination: true
        ImageId: ami-07d02ee1eeb0c996c
        InstanceType: t2.micro
        SecurityGroupIds:
          - sg-0c1617312e6017ae4

  MyASG:
    Type: AWS::AutoScaling::AutoScalingGroup
    UpdatePolicy:
      AutoScalingReplacingUpdate:
        WillReplace: True
    Properties: 
      AvailabilityZones: 
        - us-east-1a
      DesiredCapacity: 1
      HealthCheckGracePeriod: 60
      HealthCheckType: EC2
      LaunchTemplate: 
        LaunchTemplateId: !Ref MyLaunchTemplate
        Version: !GetAtt MyLaunchTemplate.LatestVersionNumber
      MaxSize: 1
      MinSize: 1
      Tags: 
        - Key: Name
          PropagateAtLaunch: True
          Value: IreneTestInstances
      VPCZoneIdentifier: 
        - subnet-05a27f6d0b0a1e195

